services:
- type: web
  name: server
  runtime: image
  image:
    url: arjunacrm/arjuna:latest
  dockerCommand: "sh -c ./scripts/render-run.sh"
  autoDeploy: false
  plan: standard
  envVars:
    - key: FRONT_BASE_URL
      fromService:
        name: server
        type: web
        envVarKey: RENDER_EXTERNAL_URL
    - key: SERVER_URL
      fromService:
        name: server
        type: web
        envVarKey: RENDER_EXTERNAL_URL
    - key: APP_SECRET
      generateValue: true
    - key: PG_DATABASE_HOST
      fromService:
        name: arjuna_postgres
        type: pserv
        property: host
    - key: PG_DATABASE_PORT
      fromService:
        name: arjuna_postgres
        type: pserv
        property: port
- type: worker
  name: worker
  runtime: image
  image:
    url: arjunacrm/arjuna:latest
  dockerCommand: "sh -c ./scripts/render-worker.sh"
  autoDeploy: false
  plan: standard
  envVars:
    - key: FRONT_BASE_URL
      fromService:
        name: server
        type: web
        envVarKey: RENDER_EXTERNAL_URL
    - key: SERVER_URL
      fromService:
        name: server
        type: web
        envVarKey: RENDER_EXTERNAL_URL
    - key: APP_SECRET
      generateValue: true
    - key: PG_DATABASE_HOST
      fromService:
        name: arjuna_postgres
        type: pserv
        property: host
    - key: PG_DATABASE_PORT
      fromService:
        name: arjuna_postgres
        type: pserv
        property: port
  disk:
    name: arjuna-disk
    mountPath: /.local-storage
    sizeGB: 5
- type: pserv
  name: arjuna_postgres
  plan: starter
  runtime: image
  image:
    url: arjunacrm/arjuna-postgres:latest
  autoDeploy: false
  disk:
    name: data
    mountPath: /var/lib/postgresql/data
    sizeGB: 10
  envVars:
  - key: POSTGRES_USER
    value: postgres
  - key: POSTGRES_PASSWORD
    value: postgres
