apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: arjunacrm-server
  name: arjunacrm-server
  namespace: arjunacrm
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: arjunacrm-server
  template:
    metadata:
      labels:
        app: arjunacrm-server
    spec:
      volumes:
        - name: arjunacrm-server-data
          persistentVolumeClaim:
            claimName: arjunacrm-server-pvc
        - name: arjunacrm-docker-data
          persistentVolumeClaim:
            claimName: arjunacrm-docker-data-pvc
      containers:
        - name: arjunacrm
          image: arjunacrm/arjuna:latest
          imagePullPolicy: Always
          env:
            - name: NODE_PORT
              value: 3000
            - name: SERVER_URL
              value: "https://crm.example.com:443"
            - name: "PG_DATABASE_URL"
              value: "postgres://postgres:postgres@arjunacrm-db.arjunacrm.svc.cluster.local/default"
            - name: "REDIS_URL"
              value: "redis://arjunacrm-redis.arjunacrm.svc.cluster.local:6379"
            - name: SIGN_IN_PREFILLED
              value: "false"
            - name: STORAGE_TYPE
              value: "local"
            - name: "ACCESS_TOKEN_EXPIRES_IN"
              value: "7d"
            - name: "LOGIN_TOKEN_EXPIRES_IN"
              value: "1h"
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: tokens
                  key: accessToken
          ports:
            - containerPort: 3000
              name: http-tcp
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /app/docker-data
              name: arjunacrm-docker-data
            - mountPath: /app/packages/arjuna-server/.local-storage
              name: arjunacrm-server-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
