apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arjunacrm-server-pvc
  namespace: arjunacrm
spec:
  storageClassName: default
  volumeName: arjunacrm-server-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
