apiVersion: v1
kind: Service
metadata:
  name: arjunacrm-server
  namespace: arjunacrm
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: http-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: arjunacrm-server
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
