apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse_datasource
    jsonData:
      server: arjuna_clickhouse
      defaultDatabase: arjuna_dev
      port: 9000
      protocol: native
      tlsSkipVerify: true
      username: default
    secureJsonData:
      password: devPassword